/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardEditRouteImport } from './routes/dashboard.edit'

const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditRoute = DashboardEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/onboard': typeof OnboardRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/explore': typeof ExploreRoute
  '/onboard': typeof OnboardRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/onboard': typeof OnboardRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/dashboard'
    | '/explore'
    | '/onboard'
    | '/dashboard/edit'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/explore'
    | '/onboard'
    | '/dashboard/edit'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/dashboard'
    | '/explore'
    | '/onboard'
    | '/dashboard/edit'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  OnboardRoute: typeof OnboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit': {
      id: '/dashboard/edit'
      path: '/edit'
      fullPath: '/dashboard/edit'
      preLoaderRoute: typeof DashboardEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEditRoute: typeof DashboardEditRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEditRoute: DashboardEditRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  OnboardRoute: OnboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
