/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardEditRouteImport } from './routes/dashboard.edit'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicOgHandleRouteImport } from './routes/api/public/og.$handle'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditRoute = DashboardEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgHandleRoute = ApiPublicOgHandleRouteImport.update({
  id: '/api/public/og/$handle',
  path: '/api/public/og/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/onboard': typeof OnboardRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/og/$handle': typeof ApiPublicOgHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/explore': typeof ExploreRoute
  '/onboard': typeof OnboardRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/og/$handle': typeof ApiPublicOgHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/onboard': typeof OnboardRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/edit': typeof DashboardEditRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/og/$handle': typeof ApiPublicOgHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/dashboard'
    | '/explore'
    | '/onboard'
    | '/wallet'
    | '/auth/callback'
    | '/dashboard/edit'
    | '/dashboard/'
    | '/api/public/og/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/explore'
    | '/onboard'
    | '/wallet'
    | '/auth/callback'
    | '/dashboard/edit'
    | '/dashboard'
    | '/api/public/og/$handle'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/dashboard'
    | '/explore'
    | '/onboard'
    | '/wallet'
    | '/auth/callback'
    | '/dashboard/edit'
    | '/dashboard/'
    | '/api/public/og/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  OnboardRoute: typeof OnboardRoute
  WalletRoute: typeof WalletRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicOgHandleRoute: typeof ApiPublicOgHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit': {
      id: '/dashboard/edit'
      path: '/edit'
      fullPath: '/dashboard/edit'
      preLoaderRoute: typeof DashboardEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$handle': {
      id: '/api/public/og/$handle'
      path: '/api/public/og/$handle'
      fullPath: '/api/public/og/$handle'
      preLoaderRoute: typeof ApiPublicOgHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardEditRoute: typeof DashboardEditRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEditRoute: DashboardEditRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  OnboardRoute: OnboardRoute,
  WalletRoute: WalletRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicOgHandleRoute: ApiPublicOgHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
